name = "bong-bong--webrtc-signal"
main = "index.ts"
compatibility_date = "2024-09-02"

account_id = "56268cde636c288343cb0767952ecf2e"
workers_dev = true

[[kv_namespaces]]
binding = "kv"
id = "e213e1b199a340b297aced2040d09f0e"

[[r2_buckets]]
binding = 'bucket'
bucket_name = 'bong-bong--webrtc-signal-store-bucket'
