name: main

on: [push]

jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - run: bunx vite build --base /bongbong/
        working-directory: packages/app

      - run: cp packages/app/dist/index.html packages/app/dist/404.html

      - run: bunx vite build --base /bongbong/webRTC-minimal-demo --outDir ../app/dist/webRTC-minimal-demo
        working-directory: packages/webRTC-demo/minimal

      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/app/dist

      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'

      - run: bunx wrangler deploy
        working-directory: packages/webRTC-signal
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - run: bun test

      # - run: bunx biome check .

      # - run: bunx tsc --noEmit
